[package]
name = "struct_macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["proc-macro"]

[dependencies]
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.66"
quote = "1.0.33"
