[package]
name = "thumb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bin16_macro = { "path" = "bin16_macro" }

colored = "2.0.0"
thiserror = "1.0.44"
